# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maps me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'Parse', '~> 1.14.2’
  # Pods for Maps me

end
